FROM debian

RUN mkdir -p /source
WORKDIR /source
RUN apt-get update && \
    apt-get install -y \
        automake \
        autotools-dev \
        bc \
        bsdmainutils \
        build-essential \
        ca-certificates \
        curl \
        git \
        libboost-all-dev \
        libdb++-dev \
        libevent-dev \
        libssl-dev \
        libtool \
        pkg-config \
        python3 \
        python3-zmq \
        wget

